### ISSUE TITLE
New 

### ISSUE THREAD

**Issue by mateowoetam** [ToCraft/Remorphed#42] opened 2024-08-17 22:21 UTC
### Mod loader

Fabric

### Minecraft version

1.21

### Remorphed version

4.0

### Woodwalkers version

5

### CraftedCore version

5.3

### Modloader version

Fabric 0.16.2

### The latest.log file

[latest.log](https://github.com/user-attachments/files/16646639/latest.log)

### Issue description

When Morphing to the Bat the bat does not have an animation, it stays in T-pose.

### Steps to reproduce

Go to the morph  menu and select Bat, once morphed into bat the model will not animate, bat stays in T-pose.

**Comment by ToCraft** [comment] 2024-08-18 07:13
Duplicate of https://github.com/ToCraft/woodwalkers-mod/issues/118

**Closed by ToCraft** 2024-08-18 07:13 UTC
Labels: bug
